apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-tempo
resources:
- ns.yaml
- tempo.yaml
- cr-tempo.yaml
- tempo-service.yaml
- tempo-patch.yaml

configMapGenerator:
- name: grafana-agent-traces

patches:
- path: agent/configmap.yaml